import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Check, X, HandCoins } from "@phosphor-icons/react";
const fmt = (n) => "$" + Math.round(n).toLocaleString("es-AR");
export default function AprobacionesTab({ group, userAddress, onApprove, onReject }) {
    if (!group)
        return _jsx("div", { className: "text-center text-muted", style: { padding: "40px 20px" }, children: "Selecciona un grupo para ver sus aprobaciones pendientes." });
    const pendingTxs = group.pending || [];
    const limit = Number(group.creditLimit);
    const totalMembers = group.members?.length || 1;
    const requiredVotes = Math.floor(totalMembers / 2) + 1;
    return (_jsxs("div", { children: [_jsx("div", { className: "header-green", style: { paddingBottom: "24px", borderBottomLeftRadius: 0, borderBottomRightRadius: 0 }, children: _jsx("div", { className: "header-top", style: { marginBottom: 0 }, children: _jsx("span", { className: "header-title", children: "Aprobaciones de Votaciones" }) }) }), _jsxs("div", { style: { background: "var(--bg-color)", padding: "16px 20px" }, children: [_jsxs("div", { style: { fontSize: "0.85rem", color: "var(--text-muted)", marginBottom: "16px" }, children: ["Solicitudes pendientes en ", group.name] }), pendingTxs.map((tx, idx) => {
                        const amount = Number(tx.amount);
                        const exceed = amount > limit;
                        const votesCount = tx.votesFor;
                        const percent = Math.min((votesCount / requiredVotes) * 100, 100);
                        return (_jsxs("div", { className: "approval-card", children: [_jsxs("div", { className: "approval-header", children: [_jsxs("div", { className: "approval-user-info", children: [_jsx("div", { className: "tx-avatar", style: { background: "var(--primary)", color: "white" }, children: tx.proposer.substring(2, 4).toUpperCase() }), _jsxs("div", { children: [_jsxs("div", { style: { fontWeight: 600 }, children: ["Miembro ", tx.proposer.substring(0, 6), "..."] }), _jsx("div", { className: "approval-time", children: "Hace 2 horas (demo)" })] })] }), _jsx("div", { className: "approval-role", children: "PROPIETARIO" })] }), _jsxs("div", { className: "approval-content", children: [_jsx("div", { className: "approval-title", children: tx.desc || "Solicitud de gasto sin descripción" }), _jsxs("div", { className: "approval-amounts", children: [_jsxs("div", { children: [_jsx("div", { className: "approval-amount-label", children: "Monto Solicitado" }), _jsx("div", { className: "approval-amount-value", children: fmt(amount * 1000) })] }), exceed && (_jsxs("div", { style: { textAlign: "right" }, children: [_jsx("div", { className: "approval-amount-label", children: "Excedente Libre" }), _jsxs("div", { className: "approval-amount-exceed", children: [fmt((amount - limit) * 1000), " ", _jsx(HandCoins, { weight: "fill", size: 16 })] })] }))] }), _jsxs("div", { className: "approval-progress", children: [_jsxs("div", { className: "progress-header", children: [_jsx("span", { children: "Votos Recibidos" }), _jsxs("span", { children: [votesCount, " / ", requiredVotes] })] }), _jsx("div", { className: "progress-bar-bg", children: _jsx("div", { className: "progress-bar-fill", style: { width: `${percent}%` } }) }), _jsx("div", { style: { fontSize: "0.75rem", color: "var(--text-muted)", marginTop: "8px" }, children: exceed ? "Al superar el límite libre, necesita votación mayoritaria para ser aprobado." : "Votación regular." })] })] }), _jsxs("div", { className: "approval-actions", children: [_jsxs("button", { className: "btn-outline", style: { display: "flex", gap: "8px", justifyContent: "center", color: "var(--danger)", borderColor: "var(--danger)" }, onClick: () => onReject(tx.id), children: [_jsx(X, { weight: "bold" }), " Rechazar"] }), _jsxs("button", { className: "btn-primary", style: { display: "flex", gap: "8px", justifyContent: "center" }, onClick: () => onApprove(tx.id), children: [_jsx(Check, { weight: "bold" }), " Aprobar"] })] })] }, idx));
                    }), pendingTxs.length === 0 && (_jsx("div", { className: "text-center text-muted", style: { padding: "40px 0" }, children: "No hay solicitudes de gasto pendientes en este momento." }))] })] }));
}
